# Settings from Frank & Petty (2020), "Sequence-to-Sequence Networks Learn the Meaning of Reflexive Anaphora"

epochs: 1000
batch_size: 1
lr: 0.01
tolerance: 0.001
patience: 1000
tf_ratio: 0.5

cuda: 0 # -1 means use CPU
