version: "3.9"
services:
  workspace:
    build: .
    environment:
      - COMPOSE_DOCKER_CLI_BUILD=1
      - DOCKER_BUILDKIT=1
    image: transductions
    entrypoint: /bin/bash
    stdin_open: true 
    tty: true
    volumes:
      - type: bind
        source: ..
        target: /home/user/transductions
    