name: transd

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.8
  - pytorch=1.8.1
  - torchtext=0.6.0
  - ipykernel=6.4.1
  - tqdm=4.62.3
  - tensorboard=2.6.0
  - pip=21.2.4
  - matplotlib=3.4.3
  - transformers=4.14.1
  - ipympl=0.7.0
  - pandas=1.3.4
  - conda-lock=0.13.2
  - pip:
    - -r requirements.txt

platforms:
 - linux-arm64