name: transd

channels:
  - pytorch

dependencies:
  - python=3.8
  - pytorch=1.9.1
  - torchtext=0.6.0
  - ipykernel=6.4.1
  - tqdm=4.62.3
  - tensorboard=2.6.0
  - pip=21.2.4
  - matplotlib=3.4.3
  - transformers
  - ipympl 
  - pandas
  - pip:
    - -r requirements.txt